<a href="https://colab.research.google.com/github/prasadnikhil125-CHAUDHARY/business-data-analysis-ai-ml/blob/main/Copy_of_4_Supply_Chain_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Supply Chain Analytics**

In [ ]:
# Upload data
import sqlite3
import requests
import pandas as pd

url = "https://github.com/YBIFoundation/SQL/raw/main/SupplyChainAdvanceAnalytics.db"

response = requests.get(url)
with open("SupplyChainAdvanceAnalytics.db", "wb") as f:
    f.write(response.content)

conn = sqlite3.connect("SupplyChainAdvanceAnalytics.db")

def sql(query):
    return pd.read_sql(query, conn)

In [ ]:
sql("SELECT * FROM supply_chain")

,Order_ID,Order_Date,Delivery_Date,Product,Category,Supplier,Warehouse,City,State,Customer_Type,...,Net_Sales,Cost_Price,Total_Cost,Profit,Shipping_Cost,Delivery_Status,Payment_Method,Delivery_Days,Customer_Rating,Order_Priority
0,100001,2026-04-23,2026-04-30,Keyboard,Accessories,XYZ Traders,Chennai WH,Bangalore,Karnataka,Wholesale,...,13500.0,586,8790,4710.0,2781,Delivered,Cash,7,3,Medium
1,100002,2026-01-10,2026-01-13,Scanner,Office Supplies,Prime Distributors,Mumbai WH,Ahmedabad,Gujarat,Retail,...,36000.0,6777,20331,15669.0,1720,Delivered,Credit Card,3,3,Low
2,100003,2026-08-05,2026-08-10,Monitor,Electronics,Tech World,Hyderabad WH,Mumbai,Maharashtra,Wholesale,...,216000.0,8609,172180,43820.0,223,Delivered,Credit Card,5,2,Medium
3,100004,2026-01-26,2026-01-28,SSD,Storage,Tech World,Hyderabad WH,Jaipur,Rajasthan,Wholesale,...,34650.0,3845,26915,7735.0,1681,Delivered,Debit Card,2,3,Medium
4,100005,2026-09-17,2026-09-22,Keyboard,Accessories,XYZ Traders,Chennai WH,Kolkata,West Bengal,Retail,...,6885.0,542,4878,2007.0,1731,Delivered,Cash,5,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109996,2026-09-25,2026-09-26,Office Desk,Furniture,ABC Suppliers,Mumbai WH,Pune,Maharashtra,Wholesale,...,270000.0,10015,180270,89730.0,2526,Delivered,UPI,1,3,Medium
9996,109997,2026-09-16,2026-09-23,Printer,Office Supplies,ABC Suppliers,Chennai WH,Lucknow,Uttar Pradesh,Retail,...,75000.0,10965,54825,20175.0,2034,Delivered,Credit Card,7,2,Medium
9997,109998,2026-06-23,2026-06-29,Router,Networking,Tech World,Delhi WH,Lucknow,Uttar Pradesh,Wholesale,...,66500.0,2128,40432,26068.0,475,Cancelled,Cash,6,5,Low
9998,109999,2026-06-15,2026-06-22,Scanner,Office Supplies,ABC Suppliers,Delhi WH,Chennai,Tamil Nadu,Wholesale,...,51000.0,8891,44455,6545.0,2909,Cancelled,Credit Card,7,4,Medium
9999,110000,2026-12-25,2026-12-27,Desktop,Electronics,XYZ Traders,Delhi WH,Jaipur,Rajasthan,Retail,...,535500.0,30889,432446,103054.0,2583,Delivered,UPI,2,3,Medium

In [ ]:
# Total records
sql("SELECT COUNT(*) FROM supply_chain")

   COUNT(*)
0     10000

In [ ]:
sql("SELECT Product,	Category FROM supply_chain")

          Product         Category
0        Keyboard      Accessories
1         Scanner  Office Supplies
2         Monitor      Electronics
3             SSD          Storage
4        Keyboard      Accessories
...           ...              ...
9995  Office Desk        Furniture
9996      Printer  Office Supplies
9997       Router       Networking
9998      Scanner  Office Supplies
9999      Desktop      Electronics

[10000 rows x 2 columns]

In [ ]:
# Electronics
sql("SELECT * FROM supply_chain WHERE Category = 'Electronics'")

,Order_ID,Order_Date,Delivery_Date,Product,Category,Supplier,Warehouse,City,State,Customer_Type,...,Net_Sales,Cost_Price,Total_Cost,Profit,Shipping_Cost,Delivery_Status,Payment_Method,Delivery_Days,Customer_Rating,Order_Priority
0,100003,2026-08-05,2026-08-10,Monitor,Electronics,Tech World,Hyderabad WH,Mumbai,Maharashtra,Wholesale,...,216000.0,8609,172180,43820.0,223,Delivered,Credit Card,5,2,Medium
1,100007,2026-08-19,2026-08-24,Laptop,Electronics,Prime Distributors,Mumbai WH,Pune,Maharashtra,Wholesale,...,52250.0,33568,33568,18682.0,2706,Delivered,Cash,5,4,High
2,100010,2026-10-05,2026-10-09,Projector,Electronics,XYZ Traders,Mumbai WH,Kolkata,West Bengal,Retail,...,396000.0,30395,334345,61655.0,1234,In Transit,UPI,4,4,Low
3,100011,2026-06-22,2026-06-27,Laptop,Electronics,XYZ Traders,Delhi WH,Lucknow,Uttar Pradesh,Wholesale,...,445500.0,37013,333117,112383.0,1908,Delivered,Cash,5,4,High
4,100013,2026-02-16,2026-02-20,Monitor,Electronics,Tech World,Mumbai WH,Hyderabad,Telangana,Wholesale,...,61200.0,9544,57264,3936.0,862,Delivered,Net Banking,4,3,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2624,109989,2026-08-08,2026-08-11,Laptop,Electronics,Prime Distributors,Hyderabad WH,Lucknow,Uttar Pradesh,Retail,...,209000.0,38486,153944,55056.0,253,Delivered,UPI,3,4,Low
2625,109990,2026-06-18,2026-06-20,Monitor,Electronics,XYZ Traders,Chennai WH,Hyderabad,Telangana,Retail,...,159600.0,8653,121142,38458.0,607,Delivered,Cash,2,4,High
2626,109993,2026-01-08,2026-01-14,Projector,Electronics,Global Supply,Delhi WH,Pune,Maharashtra,Retail,...,408000.0,29390,352680,55320.0,732,Delivered,Cash,6,2,High
2627,109994,2026-07-03,2026-07-06,Projector,Electronics,Tech World,Delhi WH,Delhi,Delhi,Retail,...,320000.0,22877,183016,136984.0,2815,In Transit,Credit Card,3,5,Medium
2628,110000,2026-12-25,2026-12-27,Desktop,Electronics,XYZ Traders,Delhi WH,Jaipur,Rajasthan,Retail,...,535500.0,30889,432446,103054.0,2583,Delivered,UPI,2,3,Medium

In [ ]:
# Net_Sales
sql("SELECT * FROM supply_chain WHERE Net_Sales>200000;")

,Order_ID,Order_Date,Delivery_Date,Product,Category,Supplier,Warehouse,City,State,Customer_Type,...,Net_Sales,Cost_Price,Total_Cost,Profit,Shipping_Cost,Delivery_Status,Payment_Method,Delivery_Days,Customer_Rating,Order_Priority
0,100003,2026-08-05,2026-08-10,Monitor,Electronics,Tech World,Hyderabad WH,Mumbai,Maharashtra,Wholesale,...,216000.0,8609,172180,43820.0,223,Delivered,Credit Card,5,2,Medium
1,100009,2026-05-05,2026-05-08,Office Desk,Furniture,Global Supply,Hyderabad WH,Jaipur,Rajasthan,Wholesale,...,255000.0,10575,179775,75225.0,849,In Transit,Net Banking,3,2,Low
2,100010,2026-10-05,2026-10-09,Projector,Electronics,XYZ Traders,Mumbai WH,Kolkata,West Bengal,Retail,...,396000.0,30395,334345,61655.0,1234,In Transit,UPI,4,4,Low
3,100011,2026-06-22,2026-06-27,Laptop,Electronics,XYZ Traders,Delhi WH,Lucknow,Uttar Pradesh,Wholesale,...,445500.0,37013,333117,112383.0,1908,Delivered,Cash,5,4,High
4,100014,2026-10-08,2026-10-12,Office Desk,Furniture,Global Supply,Hyderabad WH,Pune,Maharashtra,Retail,...,229500.0,11180,190060,39440.0,2161,Delivered,UPI,4,4,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2064,109992,2026-09-18,2026-09-20,Printer,Office Supplies,Global Supply,Chennai WH,Pune,Maharashtra,Wholesale,...,256500.0,8646,155628,100872.0,2268,In Transit,Cash,2,2,Low
2065,109993,2026-01-08,2026-01-14,Projector,Electronics,Global Supply,Delhi WH,Pune,Maharashtra,Retail,...,408000.0,29390,352680,55320.0,732,Delivered,Cash,6,2,High
2066,109994,2026-07-03,2026-07-06,Projector,Electronics,Tech World,Delhi WH,Delhi,Delhi,Retail,...,320000.0,22877,183016,136984.0,2815,In Transit,Credit Card,3,5,Medium
2067,109996,2026-09-25,2026-09-26,Office Desk,Furniture,ABC Suppliers,Mumbai WH,Pune,Maharashtra,Wholesale,...,270000.0,10015,180270,89730.0,2526,Delivered,UPI,1,3,Medium
2068,110000,2026-12-25,2026-12-27,Desktop,Electronics,XYZ Traders,Delhi WH,Jaipur,Rajasthan,Retail,...,535500.0,30889,432446,103054.0,2583,Delivered,UPI,2,3,Medium

In [ ]:
# Electronics AND >200000
sql("SELECT * FROM supply_chain WHERE Category = 'Electronics' AND Net_Sales>200000")

,Order_ID,Order_Date,Delivery_Date,Product,Category,Supplier,Warehouse,City,State,Customer_Type,...,Net_Sales,Cost_Price,Total_Cost,Profit,Shipping_Cost,Delivery_Status,Payment_Method,Delivery_Days,Customer_Rating,Order_Priority
0,100003,2026-08-05,2026-08-10,Monitor,Electronics,Tech World,Hyderabad WH,Mumbai,Maharashtra,Wholesale,...,216000.0,8609,172180,43820.0,223,Delivered,Credit Card,5,2,Medium
1,100010,2026-10-05,2026-10-09,Projector,Electronics,XYZ Traders,Mumbai WH,Kolkata,West Bengal,Retail,...,396000.0,30395,334345,61655.0,1234,In Transit,UPI,4,4,Low
2,100011,2026-06-22,2026-06-27,Laptop,Electronics,XYZ Traders,Delhi WH,Lucknow,Uttar Pradesh,Wholesale,...,445500.0,37013,333117,112383.0,1908,Delivered,Cash,5,4,High
3,100017,2026-07-31,2026-08-01,Laptop,Electronics,Tech World,Delhi WH,Kolkata,West Bengal,Wholesale,...,891000.0,34243,616374,274626.0,1186,Delivered,Debit Card,1,2,Medium
4,100025,2026-04-29,2026-05-03,Laptop,Electronics,Tech World,Delhi WH,Pune,Maharashtra,Wholesale,...,891000.0,40254,724572,166428.0,1074,Delivered,Net Banking,4,2,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1603,109982,2026-12-02,2026-12-06,Laptop,Electronics,Tech World,Chennai WH,Mumbai,Maharashtra,Retail,...,1045000.0,39059,742121,302879.0,1746,Delivered,Net Banking,4,2,High
1604,109989,2026-08-08,2026-08-11,Laptop,Electronics,Prime Distributors,Hyderabad WH,Lucknow,Uttar Pradesh,Retail,...,209000.0,38486,153944,55056.0,253,Delivered,UPI,3,4,Low
1605,109993,2026-01-08,2026-01-14,Projector,Electronics,Global Supply,Delhi WH,Pune,Maharashtra,Retail,...,408000.0,29390,352680,55320.0,732,Delivered,Cash,6,2,High
1606,109994,2026-07-03,2026-07-06,Projector,Electronics,Tech World,Delhi WH,Delhi,Delhi,Retail,...,320000.0,22877,183016,136984.0,2815,In Transit,Credit Card,3,5,Medium
1607,110000,2026-12-25,2026-12-27,Desktop,Electronics,XYZ Traders,Delhi WH,Jaipur,Rajasthan,Retail,...,535500.0,30889,432446,103054.0,2583,Delivered,UPI,2,3,Medium

In [ ]:
# Text Functions- LOWER, UPPER, TRIM
sql("SELECT Warehouse, TRIM(Warehouse) FROM supply_chain ")

         Warehouse TRIM(Warehouse)
0       Chennai WH      Chennai WH
1        Mumbai WH       Mumbai WH
2     Hyderabad WH    Hyderabad WH
3     Hyderabad WH    Hyderabad WH
4       Chennai WH      Chennai WH
...            ...             ...
9995     Mumbai WH       Mumbai WH
9996    Chennai WH      Chennai WH
9997      Delhi WH        Delhi WH
9998      Delhi WH        Delhi WH
9999      Delhi WH        Delhi WH

[10000 rows x 2 columns]

In [ ]:
# Text - LENGTH
sql("SELECT Category, Product, LENGTH(Product) FROM supply_chain")

             Category      Product  LENGTH(Product)
0         Accessories     Keyboard                8
1     Office Supplies      Scanner                7
2         Electronics      Monitor                7
3             Storage          SSD                3
4         Accessories     Keyboard                8
...               ...          ...              ...
9995        Furniture  Office Desk               11
9996  Office Supplies      Printer                7
9997       Networking       Router                6
9998  Office Supplies      Scanner                7
9999      Electronics      Desktop                7

[10000 rows x 3 columns]

In [ ]:
# REPLACE - Warehouse
sql("SELECT Warehouse, REPLACE(Warehouse,'Chennai','Madras') FROM supply_chain")

         Warehouse REPLACE(Warehouse,'Chennai','Madras')
0       Chennai WH                             Madras WH
1        Mumbai WH                             Mumbai WH
2     Hyderabad WH                          Hyderabad WH
3     Hyderabad WH                          Hyderabad WH
4       Chennai WH                             Madras WH
...            ...                                   ...
9995     Mumbai WH                             Mumbai WH
9996    Chennai WH                             Madras WH
9997      Delhi WH                              Delhi WH
9998      Delhi WH                              Delhi WH
9999      Delhi WH                              Delhi WH

[10000 rows x 2 columns]

In [ ]:
# Substring
sql("SELECT Product, SUBSTR(Product,1,3) AS Product_ID FROM supply_chain")

          Product Product_ID
0        Keyboard        Key
1         Scanner        Sca
2         Monitor        Mon
3             SSD        SSD
4        Keyboard        Key
...           ...        ...
9995  Office Desk        Off
9996      Printer        Pri
9997       Router        Rou
9998      Scanner        Sca
9999      Desktop        Des

[10000 rows x 2 columns]

In [ ]:
sql("SELECT * FROM supply_chain")

,Order_ID,Order_Date,Delivery_Date,Product,Category,Supplier,Warehouse,City,State,Customer_Type,...,Net_Sales,Cost_Price,Total_Cost,Profit,Shipping_Cost,Delivery_Status,Payment_Method,Delivery_Days,Customer_Rating,Order_Priority
0,100001,2026-04-23,2026-04-30,Keyboard,Accessories,XYZ Traders,Chennai WH,Bangalore,Karnataka,Wholesale,...,13500.0,586,8790,4710.0,2781,Delivered,Cash,7,3,Medium
1,100002,2026-01-10,2026-01-13,Scanner,Office Supplies,Prime Distributors,Mumbai WH,Ahmedabad,Gujarat,Retail,...,36000.0,6777,20331,15669.0,1720,Delivered,Credit Card,3,3,Low
2,100003,2026-08-05,2026-08-10,Monitor,Electronics,Tech World,Hyderabad WH,Mumbai,Maharashtra,Wholesale,...,216000.0,8609,172180,43820.0,223,Delivered,Credit Card,5,2,Medium
3,100004,2026-01-26,2026-01-28,SSD,Storage,Tech World,Hyderabad WH,Jaipur,Rajasthan,Wholesale,...,34650.0,3845,26915,7735.0,1681,Delivered,Debit Card,2,3,Medium
4,100005,2026-09-17,2026-09-22,Keyboard,Accessories,XYZ Traders,Chennai WH,Kolkata,West Bengal,Retail,...,6885.0,542,4878,2007.0,1731,Delivered,Cash,5,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109996,2026-09-25,2026-09-26,Office Desk,Furniture,ABC Suppliers,Mumbai WH,Pune,Maharashtra,Wholesale,...,270000.0,10015,180270,89730.0,2526,Delivered,UPI,1,3,Medium
9996,109997,2026-09-16,2026-09-23,Printer,Office Supplies,ABC Suppliers,Chennai WH,Lucknow,Uttar Pradesh,Retail,...,75000.0,10965,54825,20175.0,2034,Delivered,Credit Card,7,2,Medium
9997,109998,2026-06-23,2026-06-29,Router,Networking,Tech World,Delhi WH,Lucknow,Uttar Pradesh,Wholesale,...,66500.0,2128,40432,26068.0,475,Cancelled,Cash,6,5,Low
9998,109999,2026-06-15,2026-06-22,Scanner,Office Supplies,ABC Suppliers,Delhi WH,Chennai,Tamil Nadu,Wholesale,...,51000.0,8891,44455,6545.0,2909,Cancelled,Credit Card,7,4,Medium
9999,110000,2026-12-25,2026-12-27,Desktop,Electronics,XYZ Traders,Delhi WH,Jaipur,Rajasthan,Retail,...,535500.0,30889,432446,103054.0,2583,Delivered,UPI,2,3,Medium

In [ ]:
# Extract Year
sql("SELECT strftime('%Y', Order_Date) AS Order_Year FROM supply_chain")

     Order_Year
0          2026
1          2026
2          2026
3          2026
4          2026
...         ...
9995       2026
9996       2026
9997       2026
9998       2026
9999       2026

[10000 rows x 1 columns]

In [ ]:
# Extract Month
sql("SELECT strftime('%m', Order_Date) AS Order_Month FROM supply_chain")

     Order_Month
0             04
1             01
2             08
3             01
4             09
...          ...
9995          09
9996          09
9997          06
9998          06
9999          12

[10000 rows x 1 columns]

In [ ]:
# Extract date
sql("SELECT strftime('%d', Order_Date) AS Order_Date FROM supply_chain")

     Order_Date
0            23
1            10
2            05
3            26
4            17
...         ...
9995         25
9996         16
9997         23
9998         15
9999         25

[10000 rows x 1 columns]

In [ ]:
sql("SELECT * FROM supply_chain")

,Order_ID,Order_Date,Delivery_Date,Product,Category,Supplier,Warehouse,City,State,Customer_Type,...,Net_Sales,Cost_Price,Total_Cost,Profit,Shipping_Cost,Delivery_Status,Payment_Method,Delivery_Days,Customer_Rating,Order_Priority
0,100001,2026-04-23,2026-04-30,Keyboard,Accessories,XYZ Traders,Chennai WH,Bangalore,Karnataka,Wholesale,...,13500.0,586,8790,4710.0,2781,Delivered,Cash,7,3,Medium
1,100002,2026-01-10,2026-01-13,Scanner,Office Supplies,Prime Distributors,Mumbai WH,Ahmedabad,Gujarat,Retail,...,36000.0,6777,20331,15669.0,1720,Delivered,Credit Card,3,3,Low
2,100003,2026-08-05,2026-08-10,Monitor,Electronics,Tech World,Hyderabad WH,Mumbai,Maharashtra,Wholesale,...,216000.0,8609,172180,43820.0,223,Delivered,Credit Card,5,2,Medium
3,100004,2026-01-26,2026-01-28,SSD,Storage,Tech World,Hyderabad WH,Jaipur,Rajasthan,Wholesale,...,34650.0,3845,26915,7735.0,1681,Delivered,Debit Card,2,3,Medium
4,100005,2026-09-17,2026-09-22,Keyboard,Accessories,XYZ Traders,Chennai WH,Kolkata,West Bengal,Retail,...,6885.0,542,4878,2007.0,1731,Delivered,Cash,5,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,109996,2026-09-25,2026-09-26,Office Desk,Furniture,ABC Suppliers,Mumbai WH,Pune,Maharashtra,Wholesale,...,270000.0,10015,180270,89730.0,2526,Delivered,UPI,1,3,Medium
9996,109997,2026-09-16,2026-09-23,Printer,Office Supplies,ABC Suppliers,Chennai WH,Lucknow,Uttar Pradesh,Retail,...,75000.0,10965,54825,20175.0,2034,Delivered,Credit Card,7,2,Medium
9997,109998,2026-06-23,2026-06-29,Router,Networking,Tech World,Delhi WH,Lucknow,Uttar Pradesh,Wholesale,...,66500.0,2128,40432,26068.0,475,Cancelled,Cash,6,5,Low
9998,109999,2026-06-15,2026-06-22,Scanner,Office Supplies,ABC Suppliers,Delhi WH,Chennai,Tamil Nadu,Wholesale,...,51000.0,8891,44455,6545.0,2909,Cancelled,Credit Card,7,4,Medium
9999,110000,2026-12-25,2026-12-27,Desktop,Electronics,XYZ Traders,Delhi WH,Jaipur,Rajasthan,Retail,...,535500.0,30889,432446,103054.0,2583,Delivered,UPI,2,3,Medium

In [ ]:
sql("SELECT AVG(Shipping_Cost) FROM supply_chain")

   AVG(Shipping_Cost)
0           1605.2972

In [ ]:
sql("SELECT ROUND(AVG(Shipping_Cost),1) FROM supply_chain")

   ROUND(AVG(Shipping_Cost),1)
0                       1605.3