<a href="https://colab.research.google.com/github/prasadnikhil125-CHAUDHARY/business-data-analysis-ai-ml/blob/main/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning: Simple Linear Regression**

In [ ]:
# Step 1: Import library
import pandas as pd

https://github.com/YBIFoundation/Dataset/blob/main/Salary%20Data.csv

https://github.com/YBIFoundation/Dataset/raw/main/Salary%20Data.csv

In [ ]:
# Step 2: Read dataset
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Salary%20Data.csv')

In [ ]:
df.head()

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Experience Years  40 non-null     float64
 1   Salary            40 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 772.0 bytes

In [ ]:
df.describe()

       Experience Years         Salary
count         40.000000      40.000000
mean           5.152500   74743.625000
std            2.663715   25947.122885
min            1.100000   37731.000000
25%            3.200000   56878.250000
50%            4.600000   64472.500000
75%            6.875000   95023.250000
max           10.500000  122391.000000

In [ ]:
# Step 3: Define y (output) and X (input)
df.columns

Index(['Experience Years', 'Salary'], dtype='object')

In [ ]:
y = df['Salary']
X = df[['Experience Years']]

In [ ]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
df.shape, X.shape, X_train.shape, X_test.shape

((40, 2), (40, 1), (30, 1), (10, 1))

In [ ]:
# Step 5: Select model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

np.float64(27010.963630394683)

In [ ]:
model.coef_

array([9343.3671387])

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
# Step 8: Evaluation
from sklearn.metrics import mean_absolute_percentage_error

In [ ]:
mean_absolute_percentage_error(y_test,y_pred)

0.06230870755908321

# **Multiple Linear Regression**

In [ ]:
# Step 1: Import library
import pandas as pd

https://github.com/YBIFoundation/Dataset/blob/main/Admission%20Chance.csv


https://github.com/YBIFoundation/Dataset/raw/main/Admission%20Chance.csv

In [ ]:
# Step 2: Read dataset
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Admission%20Chance.csv')

In [ ]:
df.head()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No          400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4    SOP               400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB

In [ ]:
df.describe()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [ ]:
# Step 3: Define y (output) and X (input)
df.columns

Index(['Serial No', 'GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [ ]:
y = df['Chance of Admit ']
X = df[['GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research']]

In [ ]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
df.shape, X.shape, X_train.shape, X_test.shape

((400, 9), (400, 7), (300, 7), (100, 7))

In [ ]:
# Step 5: Select model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

np.float64(-1.250445038169678)

In [ ]:
model.coef_

array([ 0.00178135,  0.00333643,  0.00448022, -0.00363339,  0.01931061,
        0.11349064,  0.02362743])

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
# Step 8: Evaluation
from sklearn.metrics import mean_absolute_percentage_error

In [ ]:
mean_absolute_percentage_error(y_test,y_pred)

0.08239957446730994

# **Classification Prediction Model**

In [ ]:
# Step 1: Import library
import pandas as pd

https://github.com/YBIFoundation/Dataset/blob/main/Diabetes.csv

https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv

In [ ]:
# Step 2: Read dataset
df  = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv')

In [ ]:
df.head()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pregnancies  768 non-null    int64
 1   glucose      768 non-null    int64
 2   diastolic    768 non-null    int64
 3   triceps      768 non-null    int64
 4   insulin      768 non-null    int64
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64
 8   diabetes     768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.describe()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
# Step 3: Define y and X
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [ ]:
y = df['diabetes']
X = df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

In [ ]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
# Step 5: Select model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
model.intercept_

array([-8.10067506])

In [ ]:
model.coef_

array([[ 1.14289113e-01,  3.51730467e-02, -2.20166047e-02,
        -3.92083227e-03,  7.77116156e-05,  7.67728844e-02,
         1.82475649e+00,  2.19053935e-02]])

In [ ]:
# Step 7: Predict
y_pred = model.predict(X_test)

In [ ]:
# Step 8: Evaluate
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.92      0.83       118
           1       0.80      0.55      0.66        74

    accuracy                           0.78       192
   macro avg       0.78      0.73      0.74       192
weighted avg       0.78      0.78      0.77       192

# **Regression: House Price Prediction**
- Linear Regression
- KNN Regression
- Decision Tree Regression
- Random Forest

In [ ]:
# Step 1: Import library
import pandas as pd

https://github.com/YBIFoundation/Dataset/raw/main/Boston.csv

In [ ]:
# Step 2: Read dataset
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Boston.csv')

In [ ]:
df.head()

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NX       506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [ ]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
# Step 3: Define y and X
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [ ]:
y = df['MEDV']
X = df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT']]

In [ ]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
# Step 5: Select model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model = RandomForestRegressor()

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train)

RandomForestRegressor()

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
# Step 8: Evaluate
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_pred)

0.11783201244357247

# **Classification: Credit Default**
- Logistic Regression
- KNN Classifier
- Decision Tree Classifier
- Random Forest Classifier

In [ ]:
# Step 1: Import library
import pandas as pd

https://github.com/YBIFoundation/Dataset/raw/main/Credit%20Default.csv

In [ ]:
# Step 2: Read dataset
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Credit%20Default.csv')

In [ ]:
# Step 3: Define y and X
df.columns

Index(['Income', 'Age', 'Loan', 'Loan to Income', 'Default'], dtype='object')

In [ ]:
y = df['Default']
X = df[['Income', 'Age', 'Loan', 'Loan to Income']]

In [ ]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
# Step 5: Select model
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = DecisionTreeClassifier()

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
# Step 8: Evaluate
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       433
           1       1.00      1.00      1.00        67

    accuracy                           1.00       500
   macro avg       1.00      1.00      1.00       500
weighted avg       1.00      1.00      1.00       500

# **Multiple Disease Prediction - Classification**

In [ ]:
# Step 1: Import library
import pandas as pd

In [ ]:
# Step 2: Read dataset
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/MultipleDiseasePrediction.csv')

In [ ]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [ ]:
df.prognosis.value_counts()

prognosis
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [ ]:
# Step 3: Define y and X
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [ ]:
df.shape

(4920, 133)

In [ ]:
y = df['prognosis']

In [ ]:
# X = df[[ ]]
X = df.drop(['prognosis'],axis=1)

In [ ]:
# Step 4: Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2529)

In [ ]:
# Step 5: Select model
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier()

In [ ]:
# Step 6: Train model
model.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
# Step 7: Prediction
y_pred = model.predict(X_test)

In [ ]:
# Step 8: Evaluate
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
confusion_matrix(y_test,y_pred)

array([[26,  0,  0, ...,  0,  0,  0],
       [ 0, 28,  0, ...,  0,  0,  0],
       [ 0,  0, 31, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 30,  0,  0],
       [ 0,  0,  0, ...,  0, 26,  0],
       [ 0,  0,  0, ...,  0,  0, 30]])

In [ ]:
print(classification_report(y_test,y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        26
                                   AIDS       1.00      1.00      1.00        28
                                   Acne       1.00      1.00      1.00        31
                    Alcoholic hepatitis       1.00      1.00      1.00        36
                                Allergy       1.00      1.00      1.00        28
                              Arthritis       1.00      1.00      1.00        36
                       Bronchial Asthma       1.00      1.00      1.00        32
                   Cervical spondylosis       1.00      1.00      1.00        26
                            Chicken pox       1.00      1.00      1.00        26
                    Chronic cholestasis       1.00      1.00      1.00        28
                            Common Cold       1.00      1.00      1.00        36
                                 Dengue       1.00      1.00      1.00        24
                              Diabetes        1.00      1.00      1.00        29
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        31
                          Drug Reaction       1.00      1.00      1.00        26
                       Fungal infection       1.00      1.00      1.00        31
                                   GERD       1.00      1.00      1.00        22
                        Gastroenteritis       1.00      1.00      1.00        34
                           Heart attack       1.00      1.00      1.00        34
                            Hepatitis B       1.00      1.00      1.00        37
                            Hepatitis C       1.00      1.00      1.00        27
                            Hepatitis D       1.00      1.00      1.00        33
                            Hepatitis E       1.00      1.00      1.00        24
                          Hypertension        1.00      1.00      1.00        26
                        Hyperthyroidism       1.00      1.00      1.00        26
                           Hypoglycemia       1.00      1.00      1.00        28
                         Hypothyroidism       1.00      1.00      1.00        25
                               Impetigo       1.00      1.00      1.00        41
                               Jaundice       1.00      1.00      1.00        31
                                Malaria       1.00      1.00      1.00        31
                               Migraine       1.00      1.00      1.00        30
                        Osteoarthristis       1.00      1.00      1.00        35
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        36
                    Peptic ulcer diseae       1.00      1.00      1.00        25
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        29
                           Tuberculosis       1.00      1.00      1.00        38
                                Typhoid       1.00      1.00      1.00        30
                Urinary tract infection       1.00      1.00      1.00        30
                         Varicose veins       1.00      1.00      1.00        26
                            hepatitis A       1.00      1.00      1.00        30

                               accuracy                           1.00      1230
                              macro avg       1.00      1.00      1.00      1230
                           weighted avg       1.00      1.00      1.00      1230