<a href="https://colab.research.google.com/github/prasadnikhil125-CHAUDHARY/business-data-analysis-ai-ml/blob/main/SQL_Aggregate_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SQL Aggregate Functions**

In [ ]:
# Library
import sqlite3
import pandas as pd

In [ ]:
# Create database
conn = sqlite3.connect("employee.db")

If employee.db does not already exist, SQLite will automatically create it.

In [ ]:
# Create database connection
cursor = conn.cursor()

In [ ]:
# Create Employee Table
cursor.execute("CREATE TABLE IF NOT EXISTS Employee(EmployeeID INTEGER PRIMARY KEY, Name TEXT NOT NULL, Department TEXT NOT NULL, Age INTEGER, Salary REAL, Experience INTEGER, City TEXT)")

In [ ]:
conn.commit()

In [ ]:
# Create Employee Dataset
employees = [
(101,"Rahul","IT",25,55000,2,"Delhi"),
(102,"Priya","HR",28,48000,4,"Mumbai"),
(103,"Amit","Finance",35,72000,10,"Pune"),
(104,"Sneha","Marketing",30,60000,6,"Bengaluru"),
(105,"Vikas","IT",27,58000,3,"Delhi"),
(106,"Neha","Finance",32,75000,8,"Hyderabad"),
(107,"Ankit","HR",29,51000,5,"Jaipur"),
(108,"Pooja","Marketing",26,52000,2,"Lucknow"),
(109,"Rohan","IT",31,68000,7,"Noida"),
(110,"Kiran","Finance",38,90000,12,"Chennai"),
(111,"Sanjay","IT",24,50000,1,"Delhi"),
(112,"Meena","HR",33,62000,9,"Mumbai"),
(113,"Arjun","Marketing",29,57000,4,"Kolkata"),
(114,"Anjali","Finance",34,78000,9,"Pune"),
(115,"Deepak","IT",26,56000,3,"Delhi")
]

In [ ]:
cursor.executemany("INSERT INTO Employee VALUES(?,?,?,?,?,?,?)", employees)

In [ ]:
conn.commit()

In [ ]:
def sql(query):
  return pd.read_sql(query, conn)

In [ ]:
sql("SELECT * FROM EMPLOYEE")

    EmployeeID    Name Department  Age   Salary  Experience       City
0          101   Rahul         IT   25  55000.0           2      Delhi
1          102   Priya         HR   28  48000.0           4     Mumbai
2          103    Amit    Finance   35  72000.0          10       Pune
3          104   Sneha  Marketing   30  60000.0           6  Bengaluru
4          105   Vikas         IT   27  58000.0           3      Delhi
5          106    Neha    Finance   32  75000.0           8  Hyderabad
6          107   Ankit         HR   29  51000.0           5     Jaipur
7          108   Pooja  Marketing   26  52000.0           2    Lucknow
8          109   Rohan         IT   31  68000.0           7      Noida
9          110   Kiran    Finance   38  90000.0          12    Chennai
10         111  Sanjay         IT   24  50000.0           1      Delhi
11         112   Meena         HR   33  62000.0           9     Mumbai
12         113   Arjun  Marketing   29  57000.0           4    Kolkata
13         114  Anjali    Finance   34  78000.0           9       Pune
14         115  Deepak         IT   26  56000.0           3      Delhi

In [ ]:
# Retriev selected columns
sql("SELECT Name, Department FROM Employee")

      Name Department
0    Rahul         IT
1    Priya         HR
2     Amit    Finance
3    Sneha  Marketing
4    Vikas         IT
5     Neha    Finance
6    Ankit         HR
7    Pooja  Marketing
8    Rohan         IT
9    Kiran    Finance
10  Sanjay         IT
11   Meena         HR
12   Arjun  Marketing
13  Anjali    Finance
14  Deepak         IT

In [ ]:
# Select salary >60000
sql("SELECT * FROM Employee WHERE Salary >60000")

   EmployeeID    Name Department  Age   Salary  Experience       City
0         103    Amit    Finance   35  72000.0          10       Pune
1         106    Neha    Finance   32  75000.0           8  Hyderabad
2         109   Rohan         IT   31  68000.0           7      Noida
3         110   Kiran    Finance   38  90000.0          12    Chennai
4         112   Meena         HR   33  62000.0           9     Mumbai
5         114  Anjali    Finance   34  78000.0           9       Pune

In [ ]:
# Employee from Delhi
sql("SELECT * FROM Employee WHERE City = 'Delhi'")

   EmployeeID    Name Department  Age   Salary  Experience   City
0         101   Rahul         IT   25  55000.0           2  Delhi
1         105   Vikas         IT   27  58000.0           3  Delhi
2         111  Sanjay         IT   24  50000.0           1  Delhi
3         115  Deepak         IT   26  56000.0           3  Delhi

In [ ]:
# Between age 20 and 25
sql("SELECT * FROM Employee WHERE Age BETWEEN 20 AND 25")

   EmployeeID    Name Department  Age   Salary  Experience   City
0         101   Rahul         IT   25  55000.0           2  Delhi
1         111  Sanjay         IT   24  50000.0           1  Delhi

In [ ]:
# Highest Salary
sql("SELECT * FROM Employee ORDER BY Salary DESC")

    EmployeeID    Name Department  Age   Salary  Experience       City
0          110   Kiran    Finance   38  90000.0          12    Chennai
1          114  Anjali    Finance   34  78000.0           9       Pune
2          106    Neha    Finance   32  75000.0           8  Hyderabad
3          103    Amit    Finance   35  72000.0          10       Pune
4          109   Rohan         IT   31  68000.0           7      Noida
5          112   Meena         HR   33  62000.0           9     Mumbai
6          104   Sneha  Marketing   30  60000.0           6  Bengaluru
7          105   Vikas         IT   27  58000.0           3      Delhi
8          113   Arjun  Marketing   29  57000.0           4    Kolkata
9          115  Deepak         IT   26  56000.0           3      Delhi
10         101   Rahul         IT   25  55000.0           2      Delhi
11         108   Pooja  Marketing   26  52000.0           2    Lucknow
12         107   Ankit         HR   29  51000.0           5     Jaipur
13         111  Sanjay         IT   24  50000.0           1      Delhi
14         102   Priya         HR   28  48000.0           4     Mumbai

In [ ]:
# Count
sql("SELECT COUNT(*) FROM Employee")

   COUNT(*)
0        15

In [ ]:
# Average
sql("SELECT AVG(Salary) FROM Employee")

    AVG(Salary)
0  62133.333333

In [ ]:
# Max
sql("SELECT MAX(Salary) FROM Employee")

   MAX(Salary)
0      90000.0

In [ ]:
# Min age
sql("SELECT MIN(Age) FROM Employee")

   MIN(Age)
0        24

In [ ]:
# Total salary budget
sql("SELECT SUM(Salary) FROM Employee")

   SUM(Salary)
0     932000.0

In [ ]:
# Dept wise Avg Salary
sql("SELECT Department, AVG(Salary) FROM Employee GROUP BY Department")

  Department   AVG(Salary)
0    Finance  78750.000000
1         HR  53666.666667
2         IT  57400.000000
3  Marketing  56333.333333

In [ ]:
# Dept wise employee count
sql("SELECT Department, COUNT(*) FROM Employee GROUP BY Department")

  Department  COUNT(*)
0    Finance         4
1         HR         3
2         IT         5
3  Marketing         3

In [ ]:
# Dept wise highest salary
sql("SELECT Department, MAX(Salary) AS MaxSalary FROM Employee GROUP BY Department HAVING MaxSalary>65000")

  Department  MaxSalary
0    Finance    90000.0
1         IT    68000.0

In [ ]:
#
sql("SELECT Department, MAX(Salary) FROM Employee GROUP BY Department")